name:                advent-of-code
version:             2021
github:              "gumik/advent-of-code-2021"
license:             BSD3
author:              "Krzysztof Mataj"
maintainer:          "krzysztof.mataj@gmail.com"
copyright:           "2021 Krzysztof Mataj"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gumki/advent-of-code-2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - split

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code
    - containers
  